@Library('es-jenkins-shared') _
def registry = 'artifacts.trmc.osd.mil/minerva-docker'
def base = 'extension-scaffold/es-home'
def trmc_image_version = params.TRMC_IMAGE_VERSION ? params.TRMC_IMAGE_VERSION : ""

pipeline {
    agent any

    stages {
        stage('Build dc-ui container') {
            steps {
                script {
                    sh """
                    script_dir = "$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
                    docker build -t es-home "$script_dir/.." -f "$script_dir/Dockerfile"
                    """
                }
            }
        }
        stage('built-in echo testing'){
            steps {
                echo 'testing built-in echo...'
            }
        }

        stage('shared-library testEcho'){
            steps {
                testEcho()
            }
        }
    }
}