@Library('es-jenkins-shared') _

pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                testEcho()
            }
        }

        stage('test2'){

            steps {
                echo 'testing 222'
            }
        }

        stage('test3'){

            steps {
                echo 'testing 333'
            }
        }
    }
}