@Library('es-jenkins-shared') _

pipeline {
    agent any

    stages {
        stage('Build es-home container') {
            steps {
                echo 'Building es-home container...'
                script {
                    docker.build('es-home', '-f ../../Dockerfile .')
                    docker.image('es-home').run('-p 8080:8080 --name test-es-home')
                }
            }
        }
        stage('built-in echo testing'){
            steps {
                echo 'testing built-in echo...'
            }
        }

        stage('shared-library testEcho'){
            steps {
                testEcho()
            }
        }
    }
}